[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["node"]

[[build.nixpacksConfig.phases.setup]]
nixPkgs = ["nodejs_20"]

[[build.nixpacksConfig.phases.install]]
cmds = ["npm install"]

[[build.nixpacksConfig.phases.build]]
cmds = ["npm run build", "npx prisma generate"]

[deploy]
startCommand = "node .output/server/index.mjs"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[deploy.envs]
HOST = "0.0.0.0"
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"
